### ISSUE TITLE
PyV4L2Camera.exceptions.CameraError: Retrieving frame failed

### ISSUE THREAD

**Issue by duwudi** [pi-top/pi-top-Python-SDK#273]
When the camera thread fails to retrieve a frame, the following error is produced:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/pitop/camera/camera.py", line 253, in __process_camera_output
    self.__frame_handler.frame = self.__camera.get_frame()
  File "/usr/lib/python3/dist-packages/pitop/camera/core/cameras/usb_camera.py", line 35, in get_frame
    self.__camera.get_frame(),
  File "PyV4L2Camera/camera.pyx", line 225, in PyV4L2Camera.camera.Camera.get_frame (PyV4L2Camera/camera.c:3838)
  File "PyV4L2Camera/camera.pyx", line 248, in PyV4L2Camera.camera.Camera.get_frame (PyV4L2Camera/camera.c:3702)
PyV4L2Camera.exceptions.CameraError: Retrieving frame failed
```

This happens quite a lot and the next time I try and use the camera, 90% of the time I need to unplug and replug it back in. The other problem is that the program doesn't exit on this error, which means the heartbeat keeps the robot moving at the previous setting. Ideally, this error should should stop the program as a minimum, but we need a full investigation on why this happens in the first place

**Comment by m-roberts** [comment]
I agree - we should handle the exception as a priority and look into the issue in more detail to determine subsequent actions.
