### ISSUE TITLE
Wrap `grab_contours` in `try/except` for importing OpenCV

### ISSUE THREAD

**Issue by m-roberts** [pi-top/pi-top-Python-SDK#363]
```
from imutils import grab_contours
```
imports `cv2` module, it isn't wrapped in a `try/except` block. This breaks the 'OpenCV  as a soft dependency' paradigm.

```
Traceback (most recent call last):
  File "/usr/lib/pt-sys-oled/pt-sys-oled", line 21, in <module>
    from pitop.system.device import device_type
  File "/usr/lib/python3/dist-packages/pitop/__init__.py", line 36, in <module>
    from .camera import Camera
  File "/usr/lib/python3/dist-packages/pitop/camera/__init__.py", line 1, in <module>
    from .camera import Camera
  File "/usr/lib/python3/dist-packages/pitop/camera/camera.py", line 1, in <module>
    from .core import UsbCamera
  File "/usr/lib/python3/dist-packages/pitop/camera/core/__init__.py", line 8, in <module>
    from .capture_actions import (
  File "/usr/lib/python3/dist-packages/pitop/camera/core/capture_actions/__init__.py", line 5, in <module>
    from .motion_detector import MotionDetector
  File "/usr/lib/python3/dist-packages/pitop/camera/core/capture_actions/motion_detector.py", line 5, in <module>
    from pitop.processing.core.vision_functions import import_opencv
  File "/usr/lib/python3/dist-packages/pitop/processing/core/vision_functions.py", line 2, in <module>
    from imutils import grab_contours
  File "/usr/lib/python3.7/dist-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/usr/lib/python3.7/dist-packages/imutils/convenience.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by CAProjects** [comment]
just a little note to this. i installed the SDK on a headless setup and had to install all of the following in order to get the sdk to work correctly

```
sudo python3 -m pip install opencv-python
sudo apt install -y libopenjp2-7 libilmbase-dev libopenexr-dev libgstreamer1.0-dev libavcodec-dev libavformat-dev libswscale-dev
```
