### ISSUE TITLE
"SPI device not found" error when using miniscreen

### ISSUE THREAD

**Issue by jcapona** [pi-top/pi-top-Python-SDK#390]
This below error appears randomly when using the miniscreen. The screen is not usable. Some reports say their python code does not error, just doesn’t work.

Rebooting the device makes the OLED usable again.

NOTE: This appeared after the SDK supported using different SPI buses.

{code:java}$ python3 hey.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 303, in __init__
    self._spi.open(port, device)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 4, in <module>
    app = OnboardingApp()
  File "/home/pi/dev/pt-web-portal/src/miniscreen/onboarding/app.py", line 18, in __init__
    self.miniscreen = Pitop().miniscreen
  File "/usr/lib/python3/dist-packages/pitopcommon/singleton.py", line 8, in __call__
    cls.instance = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pitop/system/pitop.py", line 34, in __init__
    SupportsMiniscreen.__init__(self)
  File "/usr/lib/python3/dist-packages/pitop/core/mixins/supports_miniscreen.py", line 12, in __init__
    self._miniscreen = Miniscreen()
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/miniscreen.py", line 22, in __init__
    super(Miniscreen, self).__init__()
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 39, in __init__
    self.image = self.__empty_image
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 61, in __empty_image
    self.device.mode,
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 112, in device
    return self.__controller.get_device()
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/core/device_controller.py", line 111, in get_device
    self.__setup_device()
  File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/core/device_controller.py", line 84, in __setup_device
    gpio=None,
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 314, in __init__
    raise luma.core.error.DeviceNotFoundError('SPI device not found')
luma.core.error.DeviceNotFoundError: SPI device not found{code}

**Comment by duwudi** [comment]
Can confirm I also see this quite often, are we removing luma as a dependency in future? Just trying to figure out if we should tackle this now or after that work is done
